Update theming.mdx
rebassjs/rebass pull request #1047
Opened 2020-11-14 20:39 UTC by mberneti

Replaced deprecated `emotion-theming` package with `@emotion/react`

2020-11-22 23:40 UTC, Flavien-Pensato approved these changes

2020-11-23 00:39 UTC, Flavien-Pensato requested changes
@emotion/react is not compatible with the current version of emotion.

https://github.com/rebassjs/rebass/pull/1051

2020-11-25 20:54 UTC, stramel commented
This could probably be closed in favor of the #1051

2020-12-12 16:13 UTC, mberneti commented
@stramel Of curse.

2020-12-12 16:13 UTC, closed without merging